# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: psi.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpsi.proto\x12\x03psi\x1a\x1bgoogle/protobuf/empty.proto\"%\n\x14PrepareForPSIRequest\x12\r\n\x05index\x18\x01 \x01(\r\"+\n\x19SendEncryptedArrayRequest\x12\x0e\n\x06values\x18\x01 \x01(\x0c\x32\xa0\x01\n\x0c\x44\x61taTransfer\x12\x42\n\rPrepareForPSI\x12\x19.psi.PrepareForPSIRequest\x1a\x16.google.protobuf.Empty\x12L\n\x12SendEncryptedArray\x12\x1e.psi.SendEncryptedArrayRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'psi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREPAREFORPSIREQUEST']._serialized_start=47
  _globals['_PREPAREFORPSIREQUEST']._serialized_end=84
  _globals['_SENDENCRYPTEDARRAYREQUEST']._serialized_start=86
  _globals['_SENDENCRYPTEDARRAYREQUEST']._serialized_end=129
  _globals['_DATATRANSFER']._serialized_start=132
  _globals['_DATATRANSFER']._serialized_end=292
# @@protoc_insertion_point(module_scope)
